# Generated by Django 5.1.2 on 2024-11-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_answer_voter_alter_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
